### ISSUE TITLE
数据集的问题

### ISSUE THREAD

**Issue by ldlshizhu** [megvii-model/HINet#11]
我按照您的方式组织了数据集的结构，但是报错：
FileNotFoundError: [Errno 2] No such file or directory: './datasets/GoPro/train/blur_crops.lmdb/meta_info.txt'
请问’blur_crops.lmdb/meta_info.txt‘是什么呢 我该如何解决

**Comment by mayorx** [comment]
ldlshizhu, 您好:

感谢对HINet的关注！
在组织好数据集后， 如README所描述的，您需要运行 python scripts/data_preparation/gopro.py 来完成剩下的两步工作
1. 切割图片为 512x512 patch，
2. 将数据处理成lmdb格式
以上两步均是为了加快训练速度。其中第二步会添加 blur_crops.lmdb/meta_info.txt 等文件。

(不推荐）您也可以选择绕过这两步，直接在原图上训练，但此时训练时间会增加许多。
此时需要将训练的config文件(以 options/train/GoPro/HINet.yml 为例）中的 dataroot_gt， dataroot_lq切换为无 .lmdb 后缀的文件夹地址。该文件夹中应直接包含所有数据图片。 然后将 io_backend 中的type切换为 disk。见[此处](https://github.com/xinntao/BasicSR/blob/master/docs/DatasetPreparation.md#how-to-use)的第一个例子.


附：[数据准备相关文档](https://github.com/xinntao/BasicSR/blob/master/docs/DatasetPreparation.md#dataset-preparation)

**Comment by ldlshizhu** [comment]
感谢您的耐心回复！
我确实运行了scripts/data_preparation/gopro.py文件进行数据处理，但是会中途exit。我看terminal打印出来的，已经创建了blur_crops和sharp_crops，并且显示All processes done. 紧接着就会报错：IndexError: list index out of range 具体的错误信息我复制来了，您可以帮我看看吗，说是下标溢出……对了，我在project/PycharmProjects/HINet-main1/datasets下创建数据集的软链接，但是在scripts/data_preparation/gopro.py代码中我把input_folder和save_folder的地址都写为gopro数据集的真实地址：
opt['input_folder'] = '/common_sda/ldl_dataset/GoPro/train/input'
opt['save_folder'] = '/common_sda/ldl_dataset/GoPro/train/blur_crops'
opt['input_folder'] = '/common_sda/ldl_dataset/GoPro/train/target'
opt['save_folder'] = '/common_sda/ldl_dataset/GoPro/train/sharp_crops'
我报错的信息是下面的：
mkdir /common_sda/ldl_dataset/GoPro/train/blur_crops ...
Extract: 100%|█████████▉| 2094/2103 [02:51<00:00, 16.35image/s]All processes done.
Extract: 100%|██████████| 2103/2103 [02:51<00:00, 12.28image/s]
mkdir /common_sda/ldl_dataset/GoPro/train/sharp_crops ...
Extract: 100%|█████████▉| 2101/2103 [02:14<00:00, 28.59image/s]All processes done.
Reading image path list ...
Create lmdb for HINet-main1/datasets/GoPro/train/blur_crops, save to HINet-main1/datasets/GoPro/train/blur_crops.lmdb...
Totoal images: 0
Extract: 100%|██████████| 2103/2103 [02:14<00:00, 15.59image/s]
Traceback (most recent call last):
  File "/home/ldl/project/PycharmProjects/HINet-main1/scripts/data_preparation/gopro.py", line 125, in <module>
    main()
  File "/home/ldl/project/PycharmProjects/HINet-main1/scripts/data_preparation/gopro.py", line 33, in main
    create_lmdb_for_gopro()
  File "/home/ldl/project/PycharmProjects/HINet-main1/basicsr/utils/create_lmdb.py", line 51, in create_lmdb_for_gopro
    make_lmdb_from_imgs(folder_path, lmdb_path, img_path_list, keys)
  File "/home/ldl/project/PycharmProjects/HINet-main1/basicsr/utils/lmdb_util.py", line 100, in make_lmdb_from_imgs
    osp.join(data_path, img_path_list[0]), cv2.IMREAD_UNCHANGED)
IndexError: list index out of range
麻烦您帮我看一下呢

**Comment by ldlshizhu** [comment]
> 感谢您的耐心回复！
> 我确实运行了scripts/data_preparation/gopro.py文件进行数据处理，但是会中途exit。我看terminal打印出来的，已经创建了blur_crops和sharp_crops，并且显示All processes done. 紧接着就会报错：IndexError: list index out of range 具体的错误信息我复制来了，您可以帮我看看吗，说是下标溢出……对了，我在project/PycharmProjects/HINet-main1/datasets下创建数据集的软链接，但是在scripts/data_preparation/gopro.py代码中我把input_folder和save_folder的地址都写为gopro数据集的真实地址：
> opt['input_folder'] = '/common_sda/ldl_dataset/GoPro/train/input'
> opt['save_folder'] = '/common_sda/ldl_dataset/GoPro/train/blur_crops'
> opt['input_folder'] = '/common_sda/ldl_dataset/GoPro/train/target'
> opt['save_folder'] = '/common_sda/ldl_dataset/GoPro/train/sharp_crops'
> 我报错的信息是下面的：
> mkdir /common_sda/ldl_dataset/GoPro/train/blur_crops ...
> Extract: 100%|█████████▉| 2094/2103 [02:51<00:00, 16.35image/s]All processes done.
> Extract: 100%|██████████| 2103/2103 [02:51<00:00, 12.28image/s]
> mkdir /common_sda/ldl_dataset/GoPro/train/sharp_crops ...
> Extract: 100%|█████████▉| 2101/2103 [02:14<00:00, 28.59image/s]All processes done.
> Reading image path list ...
> Create lmdb for HINet-main1/datasets/GoPro/train/blur_crops, save to HINet-main1/datasets/GoPro/train/blur_crops.lmdb...
> Totoal images: 0
> Extract: 100%|██████████| 2103/2103 [02:14<00:00, 15.59image/s]
> Traceback (most recent call last):
> File "/home/ldl/project/PycharmProjects/HINet-main1/scripts/data_preparation/gopro.py", line 125, in
> main()
> File "/home/ldl/project/PycharmProjects/HINet-main1/scripts/data_preparation/gopro.py", line 33, in main
> create_lmdb_for_gopro()
> File "/home/ldl/project/PycharmProjects/HINet-main1/basicsr/utils/create_lmdb.py", line 51, in create_lmdb_for_gopro
> make_lmdb_from_imgs(folder_path, lmdb_path, img_path_list, keys)
> File "/home/ldl/project/PycharmProjects/HINet-main1/basicsr/utils/lmdb_util.py", line 100, in make_lmdb_from_imgs
> osp.join(data_path, img_path_list[0]), cv2.IMREAD_UNCHANGED)
> IndexError: list index out of range
> 麻烦您帮我看一下呢

啊我解决了，我太菜了。谢谢您，这个问题可以关闭了。

**Comment by Cassieyy** [comment]
> > 感谢您的耐心回复！
> > 我确实运行了scripts/data_preparation/gopro.py文件进行数据处理，但是会中途exit。我看terminal打印出来的，已经创建了blur_crops和sharp_crops，并且显示All processes done. 紧接着就会报错：IndexError: list index out of range 具体的错误信息我复制来了，您可以帮我看看吗，说是下标溢出……对了，我在project/PycharmProjects/HINet-main1/datasets下创建数据集的软链接，但是在scripts/data_preparation/gopro.py代码中我把input_folder和save_folder的地址都写为gopro数据集的真实地址：
> > opt['input_folder'] = '/common_sda/ldl_dataset/GoPro/train/input'
> > opt['save_folder'] = '/common_sda/ldl_dataset/GoPro/train/blur_crops'
> > opt['input_folder'] = '/common_sda/ldl_dataset/GoPro/train/target'
> > opt['save_folder'] = '/common_sda/ldl_dataset/GoPro/train/sharp_crops'
> > 我报错的信息是下面的：
> > mkdir /common_sda/ldl_dataset/GoPro/train/blur_crops ...
> > Extract: 100%|█████████▉| 2094/2103 [02:51<00:00, 16.35image/s]All processes done.
> > Extract: 100%|██████████| 2103/2103 [02:51<00:00, 12.28image/s]
> > mkdir /common_sda/ldl_dataset/GoPro/train/sharp_crops ...
> > Extract: 100%|█████████▉| 2101/2103 [02:14<00:00, 28.59image/s]All processes done.
> > Reading image path list ...
> > Create lmdb for HINet-main1/datasets/GoPro/train/blur_crops, save to HINet-main1/datasets/GoPro/train/blur_crops.lmdb...
> > Totoal images: 0
> > Extract: 100%|██████████| 2103/2103 [02:14<00:00, 15.59image/s]
> > Traceback (most recent call last):
> > File "/home/ldl/project/PycharmProjects/HINet-main1/scripts/data_preparation/gopro.py", line 125, in
> > main()
> > File "/home/ldl/project/PycharmProjects/HINet-main1/scripts/data_preparation/gopro.py", line 33, in main
> > create_lmdb_for_gopro()
> > File "/home/ldl/project/PycharmProjects/HINet-main1/basicsr/utils/create_lmdb.py", line 51, in create_lmdb_for_gopro
> > make_lmdb_from_imgs(folder_path, lmdb_path, img_path_list, keys)
> > File "/home/ldl/project/PycharmProjects/HINet-main1/basicsr/utils/lmdb_util.py", line 100, in make_lmdb_from_imgs
> > osp.join(data_path, img_path_list[0]), cv2.IMREAD_UNCHANGED)
> > IndexError: list index out of range
> > 麻烦您帮我看一下呢
> 
> 啊我解决了，我太菜了。谢谢您，这个问题可以关闭了。

可不可以请问一下您是怎么解决的呢 我也遇到相似的问题了 希望能得到您的帮助！

**Comment by mayorx** [comment]
> > > 感谢您的耐心回复！
> > > 我确实运行了scripts/data_preparation/gopro.py文件进行数据处理，但是会中途exit。我看terminal打印出来的，已经创建了blur_crops和sharp_crops，并且显示All processes done. 紧接着就会报错：IndexError: list index out of range 具体的错误信息我复制来了，您可以帮我看看吗，说是下标溢出……对了，我在project/PycharmProjects/HINet-main1/datasets下创建数据集的软链接，但是在scripts/data_preparation/gopro.py代码中我把input_folder和save_folder的地址都写为gopro数据集的真实地址：
> > > opt['input_folder'] = '/common_sda/ldl_dataset/GoPro/train/input'
> > > opt['save_folder'] = '/common_sda/ldl_dataset/GoPro/train/blur_crops'
> > > opt['input_folder'] = '/common_sda/ldl_dataset/GoPro/train/target'
> > > opt['save_folder'] = '/common_sda/ldl_dataset/GoPro/train/sharp_crops'
> > > 我报错的信息是下面的：
> > > mkdir /common_sda/ldl_dataset/GoPro/train/blur_crops ...
> > > Extract: 100%|█████████▉| 2094/2103 [02:51<00:00, 16.35image/s]All processes done.
> > > Extract: 100%|██████████| 2103/2103 [02:51<00:00, 12.28image/s]
> > > mkdir /common_sda/ldl_dataset/GoPro/train/sharp_crops ...
> > > Extract: 100%|█████████▉| 2101/2103 [02:14<00:00, 28.59image/s]All processes done.
> > > Reading image path list ...
> > > Create lmdb for HINet-main1/datasets/GoPro/train/blur_crops, save to HINet-main1/datasets/GoPro/train/blur_crops.lmdb...
> > > Totoal images: 0
> > > Extract: 100%|██████████| 2103/2103 [02:14<00:00, 15.59image/s]
> > > Traceback (most recent call last):
> > > File "/home/ldl/project/PycharmProjects/HINet-main1/scripts/data_preparation/gopro.py", line 125, in
> > > main()
> > > File "/home/ldl/project/PycharmProjects/HINet-main1/scripts/data_preparation/gopro.py", line 33, in main
> > > create_lmdb_for_gopro()
> > > File "/home/ldl/project/PycharmProjects/HINet-main1/basicsr/utils/create_lmdb.py", line 51, in create_lmdb_for_gopro
> > > make_lmdb_from_imgs(folder_path, lmdb_path, img_path_list, keys)
> > > File "/home/ldl/project/PycharmProjects/HINet-main1/basicsr/utils/lmdb_util.py", line 100, in make_lmdb_from_imgs
> > > osp.join(data_path, img_path_list[0]), cv2.IMREAD_UNCHANGED)
> > > IndexError: list index out of range
> > > 麻烦您帮我看一下呢
> > 
> > 
> > 啊我解决了，我太菜了。谢谢您，这个问题可以关闭了。
> 
> 可不可以请问一下您是怎么解决的呢 我也遇到相似的问题了 希望能得到您的帮助！


您好， 我没有遇到过该问题。 如果是根据报错的话， 应该是 “img_path_list” 为空了, 可能原因是一些文件没有按照README描述的位置组织， 见此： https://github.com/megvii-model/HINet/blob/main/basicsr/utils/create_lmdb.py#L52-L75

**Comment by dbrown240** [comment]
I ran into this issue, as well, however, my images in /input and /target were .jpg files opposed to .png files. All I had to do to fix this step was to edit the create_lmdb_for_gopro function in basicsr/utils/create_lmdb.py to pass "jpg" instead of "png"

`def create_lmdb_for_gopro():
    folder_path = './datasets/GoPro/train/blur_crops'
    lmdb_path = './datasets/GoPro/train/blur_crops.lmdb'

    img_path_list, keys = prepare_keys(folder_path, 'jpg')
    make_lmdb_from_imgs(folder_path, lmdb_path, img_path_list, keys)

    folder_path = './datasets/GoPro/train/sharp_crops'
    lmdb_path = './datasets/GoPro/train/sharp_crops.lmdb'

    img_path_list, keys = prepare_keys(folder_path, 'jpg')
    make_lmdb_from_imgs(folder_path, lmdb_path, img_path_list, keys)`

**Comment by Cassieyy** [comment]
您的邮件已收到哦我会及时处理哒~

**Comment by ldlshizhu** [comment]
> 你的邮件已经收到哦我会及时处理哒~

非常非常感谢！通过作者们的耐心解答我已成功训练，效果非常棒！
