### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by Dominic-ZZ** [megvii-model/HINet#12]
1.大量的import报错
2.输入的数据需要是lmdb格式的？```ValueError: lq folder and gt folder should both in lmdb formats. But received lq: ./datasets/de_white/train/input; gt: ./datasets/de_white/train/target```

**Comment by mayorx** [comment]
Dominic-ZZ , 您好：

关于import 报错， 能否提供更详细的信息？ 关于HINet的安装， 见此： https://github.com/megvii-model/HINet#installation
关于输入数据， lmdb格式可以加速训练但不是必须的， 可以将  io_backend 中的type 设置为 disk。您可以参考[这个文档](https://github.com/xinntao/BasicSR/blob/master/docs/DatasetPreparation.md#Data-Storage-Format)

**Comment by Dominic-ZZ** [comment]
> Dominic-ZZ , 您好：
> 
> 关于import 报错， 能否提供更详细的信息？ 关于HINet的安装， 见此： https://github.com/megvii-model/HINet#installation
> 关于输入数据， lmdb格式可以加速训练但不是必须的， 可以将 io_backend 中的type 设置为 disk。您可以参考[这个文档](https://github.com/xinntao/BasicSR/blob/master/docs/DatasetPreparation.md#Data-Storage-Format)

谢谢
