### ISSUE TITLE
Question of chunk function in the HIN Block

### ISSUE THREAD

**Issue by FanChiMao** [megvii-model/HINet#14]
Hello, 

I'm a student learning the image restoration lately. 
I recently study the architecture of HINet, and I really appreciate you to provide the complete code.

And I have a question about the HIN Block.
I want to know why you use chunk function to split feature's channels to two parts in the beginning of HIN Block,
rather than using the whole channel feature after 3x3 convolution. 
Then, use aggregation or concatenation to fuse two feature maps.
Or you had done some experiments to summarize the final architecture. I want to realize your idea~!

Thank you!

**Comment by Rookielike** [comment]
hi FanChiMao，
here is the code of HIN Block https://github.com/megvii-model/HINet/blob/6557226817df6e3b35f4329f1040c0e02a80040c/basicsr/models/archs/hinet_arch.py#L151-L168. We use chunk function after the first 3x3 convolution as you think.  And we did some ablation experiments about HIN Block in section4.3 to prove that the current structure is optimal (we didn't try to add half instance norm after every 3x3 conv in a HIN Block. you can try ).

**Comment by FanChiMao** [comment]
Thank you for your reply very much~! I will try your suggestion in the future!
