### ISSUE TITLE
训练设置

### ISSUE THREAD

**Issue by zhangheng-h** [megvii-model/HINet#18]
你好，请问在只有两张卡的情况下，该如何设置初始学习率和训练的迭代次数呢？

**Comment by mayorx** [comment]
HI, zhangheng-h,

很难说2张卡下应该怎么设置新的setting。一般情况下，可以参考这里的做法：
https://github.com/megvii-model/HINet/issues/15#issuecomment-881678745

即，尽量保证模型“看到”的pixels总数相同，约 8(gpus) x 8 (batch_size) x 256 x 256 (crop_size) x 400000 (iters), 然后根据您那边的实际情况（如显卡数量，显存大小）修改 这里几个值。

在上一步完成之后，调整学习率。您可以尝试运行1000～2000 iters看下loss曲线是否正常，然后选择合适的学习率。

感谢

**Comment by zhangheng-h** [comment]
感谢回复
