### ISSUE TITLE
Size miss matched 

### ISSUE THREAD

**Issue by BhavyaSoni31** [megvii-model/HINet#19]
When running the SIDD-1x pre trained model this error generated. 

```
\basicsr\models\archs\hinet_arch.py", line 179, in forward
out = torch.cat([up, bridge], 1)
RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 1. Got 10 and 11 in dimension 2 (The offen
ding index is 1)

```

**Comment by mayorx** [comment]
Hi BhavyaSoni31,

That might be because the input image height length && width length are not a multiple of 32,
you can try padding the input image with zeros.
