### ISSUE TITLE
About the test results

### ISSUE THREAD

**Issue by hellogry** [megvii-model/HINet#2]
How can I show the image after the test?

**Comment by Rookielike** [comment]
Take SIDD for example，set  "save_image" flag to Ture in options/test/SIDD/HINet-SIDD-1x.yml. And outputs will be saved in the folder in which checkpoints be saved

**Comment by hellogry** [comment]
hello, how can i test the real rain12 dataset?

**Comment by mayorx** [comment]
> hello, how can i test the real rain12 dataset?

Hi, hellogry, Rain12 is been included in the rain13k dataset. If you want to test it individually, I recommend you replace the [groundtruth and input path](https://github.com/megvii-model/HINet/blob/main/options/test/Rain13k/HINet-Test100.yml#L15-L16) to your rain12 dataset and make a new test config file, ie. HINet-Rain12.yml .
