### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3, 64, 3, 3]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

### ISSUE THREAD

**Issue by hellogry** [megvii-model/HINet#20]
When I used your model and wrote my own training code, I found a bug.

def main(opt):

    loader_train = getDataLoader(opt)
    model = getModel(opt)
    model_saver = utils.modelSaver(opt['save_path'], opt['save_freq'])
    criterion = nn.L1Loss()
    model, criterion = updateGPU(model, criterion, opt)
    optimizer, scheduler = getOptimizer(model, opt)

    last_avg_psnr = 0
    last_avg_loss = 0
    for epoch in range(0, opt['epochs']):
        
        scheduler.step(epoch)
        avg_psnr = 0
        avg_loss = 0

        num_iterations = len(loader_train)
        num_iter_counts = 0
        l_total = 0
        loss = 0.
        for i, (input_train, target_train) in enumerate(loader_train):

            if(random.random() > opt['sampling_rate']):
                continue

            num_iter_counts += 1

            model.train()
            model.zero_grad()
            optimizer.zero_grad()

            input_train = Variable(input_train)
            target_train = Variable(target_train)
            
            if opt['use_gpu']:
                input_train = input_train.cuda()
                target_train = target_train.cuda()
            
            out_train = model(input_train)
            if not isinstance(out_train, list):
                out_train = [out_train]
            for pred in out_train:

                loss += criterion(target_train, pred)
            torch.autograd.set_detect_anomaly(True)
            loss.backward(retain_graph=True)
            optimizer.step()

            model.eval()
            out_train= model(input_train)
            for pp in out_train:
                pp += torch.clamp(pp, 0., 1.)
            psnr_train = utils.batch_PSNR(pp, target_train, 1.)
            avg_psnr += psnr_train 
            avg_loss += loss.item() 
                
            print("[epoch %d/%d][%d/%d], last avg loss: %.4f, avg PSNR: %.4f" % (epoch+1, opt['epochs'], i+1, num_iterations, last_avg_loss, last_avg_psnr), end='\r')

        # macs, params = get_model_complexity_info(model, (3, 80, 80), as_strings=True,
        #                                          print_per_layer_stat=True, verbose=True)
        # print('{:<30}  {:<8}'.format('Computational complexity: ', macs))
        # print('{:<30}  {:<8}'.format('Number of parameters: ', params))
        last_avg_psnr = avg_psnr / (num_iter_counts * 1.0)
        last_avg_loss = avg_loss / (num_iter_counts * 1.0)
        model_saver.saveModel(model, epoch, last_avg_psnr)

  File "/home/szp/src/train.py", line 158, in <module>
    main(opt)
  File "/home/szp/src/train.py", line 105, in main
    loss.backward(retain_graph=True)
  File "/home/szp/.local/lib/python3.6/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/szp/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3, 64, 3, 3]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

Process finished with exit code 1

**Comment by hellogry** [comment]
我自己写了一个训练程序，您论文上用的l1loss吧？然后将两个阶段网络输出loss相加，就报了个错误

**Comment by hellogry** [comment]
因为您的训练代码似乎有点复杂，我就直接拿了网络出来训练

**Comment by mayorx** [comment]
Hi, hellogry, 

感谢您对HINet的关注！我没有碰到过上述情况，但是根据报错以及您的代码，我猜测问题可能出现在

```
       for pred in out_train:
            loss += criterion(target_train, pred)
```
在第二个iter开始时由于loss没有置0，导致还残留上一个iter的loss导致的问题。

可以在对loss求和之前, 先将loss设置为0，应该可以修复该问题：
```
       loss = 0.
       for pred in out_train:
            loss += criterion(target_train, pred)
```

**Comment by mayorx** [comment]
由于1个月没有消息， 故先将该issue close
