### ISSUE TITLE
Pretrained model settings in SIDD model

### ISSUE THREAD

**Issue by pettod** [megvii-model/HINet#21]
Hi,

Which settings should be used when using SIDD pretrained model and to run demo.py? Especially the lines in the following file are having mismatches when using different pretrained model than the deblurring example.
 
https://github.com/megvii-model/HINet/blob/main/options/demo/demo.yml#L20-L24

**Comment by Rookielike** [comment]
The training setting of SIDD is the same as that of deblur. The only difference is the setting of the model:
![image](https://user-images.githubusercontent.com/28975635/129518086-72d035f2-0450-457a-8eb6-af65d4a15e3f.png)
When running the demo.py for denoising, you need to change hin_ position_left from 3 to 0

**Comment by pettod** [comment]
Great thank you, found the `hin_position` parameter values from `options/test/SIDD`
