### ISSUE TITLE
Did it work on image dehazing task？

### ISSUE THREAD

**Issue by EKChloe** [megvii-model/HINet#3]
▲
Is this wonderful HINet useful for image dehazing

**Comment by mayorx** [comment]
Hi, EKChloe 
We have not tried the dehazing task yet, but I see no reason why it is not effective on the dehazing task.
Please feel free to use HINet for your task and we are grateful if you could share your results with us.

**Comment by EKChloe** [comment]
ok ，and I will try your HIN block on dehazing task in my free time
