### ISSUE TITLE
在训练中的一些疑问

### ISSUE THREAD

**Issue by Dengshunge** [megvii-model/HINet#30]
你好，感谢你开源如此棒的源码。
我在训练HINet时，遇到几个问题，想和你探讨一下。
1. 在推理时，你的做法是分块进行推理。但分块推理会造成图片的不对齐，有明显的裂缝。请问这个该如何解决呢？使用全图进行推理吗？
2. 在预测时，对于同一张图，有些区域的效果会好，但有些区域的效果会变更差（例如变得更加模糊），请问有遇到过这个问题吗？可能是那里出现了问题呢？
3. 在实际应用中，图片可能是清晰的，是否有一个判断准则，来判断图片清晰而不进行denoise或者deblur呢？
谢谢。

**Comment by mayorx** [comment]
Dengshunge，你好，

感谢对HINet的关注。
是的，用全图测试应该可以避免1， 2所说的问题。
关于3， 可能可以单独训练一个轻量级的判别器辅助判断图片的清晰程度， 但是我暂未有实验结果。

**Comment by Dengshunge** [comment]
@mayorx 好的，谢谢你的回复。
