### ISSUE TITLE
关于损失函数和hin block

### ISSUE THREAD

**Issue by ldlshizhu** [megvii-model/HINet#35]
您好，感谢您做出的杰出的贡献！
想请教您是否在损失函数上可以结合一些其他的函数以便更能发挥网络的优点

**Comment by mayorx** [comment]
您好，
我们并没有特别针对损失函数进行消融实验， 您可以尝试结合其他的函数比如perceptual loss等，相信能有更好的结果.
对于它为什么work还没有一个很好的解释，可能可以算成是隐患吧。

**Comment by ldlshizhu** [comment]
> 您好， 我们并没有特别针对损失函数进行消融实验， 您可以尝试结合其他的函数比如perceptual loss等，相信能有更好的结果. 对于它为什么work还没有一个很好的解释，可能可以算成是隐患吧。

谢谢您的耐心回答~
请问代码中打印的HINet, with parameters:135,860,870 它的单位是什么呢？和FLOPs有关吗？
期待您的解答~

**Comment by mayorx** [comment]
您好， 这里是指HINet的参数量， 并不是Flops。

**Comment by ldlshizhu** [comment]
请问它的单位应为？


---原始邮件---
发件人: &quot;Chen ***@***.***&gt;
发送时间: 2022年2月6日(周日) 晚上8:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [megvii-model/HINet] 关于损失函数和hin block (Issue #35)




 
您好， 这里是指HINet的参数量， 并不是Flops。
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mayorx** [comment]
您好， 单位为“个”，计算代码见： https://github.com/megvii-model/HINet/blob/0cfa28b930da36316dea0bed75f8a49630039085/basicsr/models/base_model.py#L139

**Comment by ldlshizhu** [comment]
> 您好， 单位为“个”，计算代码见：
> 
> https://github.com/megvii-model/HINet/blob/0cfa28b930da36316dea0bed75f8a49630039085/basicsr/models/base_model.py#L139

非常感谢您！请问该参数量能否反应网络“轻便”程度，一直对这个参数的意义不大明确，还请您帮忙解答

**Comment by ldlshizhu** [comment]
> > 您好， 单位为“个”，计算代码见：
> > https://github.com/megvii-model/HINet/blob/0cfa28b930da36316dea0bed75f8a49630039085/basicsr/models/base_model.py#L139
> 
> 非常感谢您！请问该参数量能否反应网络“轻便”程度，一直对这个参数的意义不大明确，还请您帮忙解答

并且我运行去模糊的部分，打印出的参数个数为135,860,870，为何是88M呢。实在抱歉问您这么多问题

**Comment by mayorx** [comment]
您可以尝试下如下代码：

```
    net = HINet()
    t = 0
    for p in net.parameters():
        t += p.numel()
    print(f'params: {t}')
```

在HINet默认超参下， 参数量应为 88.7M 左右
至于为何会出现135.86M， 暂时未确认原因。


参数量可以作为这个算法的 “空间复杂度” 的一部分（另外一部分是运行时的空间消耗）




> > > 您好， 单位为“个”，计算代码见：
> > > https://github.com/megvii-model/HINet/blob/0cfa28b930da36316dea0bed75f8a49630039085/basicsr/models/base_model.py#L139
> > 
> > 
> > 非常感谢您！请问该参数量能否反应网络“轻便”程度，一直对这个参数的意义不大明确，还请您帮忙解答
> 
> 并且我运行去模糊的部分，打印出的参数个数为135,860,870，为何是88M呢。实在抱歉问您这么多问题

**Comment by ldlshizhu** [comment]
非常感谢您的耐心回答！
