### ISSUE TITLE
Inference code for a single image

### ISSUE THREAD

**Issue by p1x31** [megvii-model/HINet#4]
Great job creators! Very impressive work!
I wonder what book influenced your python skills the most. 

Is this project adopting the MPRNets' license?

Any plans for realising inference code for a single image. E.g demo code.  If not maybe I can submit a pull request, any preferences for a way it should be formalized?

Keep it up!

**Comment by Rookielike** [comment]
Thank you for your comments.  You are welcome to submit your pull request，and It would be great if the code of demo could be simpler.

**Comment by mayorx** [comment]
> Great job creators! Very impressive work!
> I wonder what book influenced your python skills the most.
> 
> Is this project adopting the MPRNets' license?
> 
> Any plans for realising inference code for a single image. E.g demo code. If not maybe I can submit a pull request, any preferences for a way it should be formalized?
> 
> Keep it up!

Hi, p1x31,

We have provided [single image inference](https://github.com/megvii-model/HINet#quick-start-single-image-inference) demo (GoPro in default).
And this project is under the MIT License,  feel free to play with it : )

**Comment by p1x31** [comment]
Can confirm I was able to reproduce your results for denoise, deblur and derain. Thank you for an update!
