### ISSUE TITLE
Question about denoising task

### ISSUE THREAD

**Issue by hwayoon2** [megvii-model/HINet#43]
Hi thank you for the great work
I have a question about denoising task (training SIDD)

In the options, it seems like training SIDD only use L1 loss not PSNR loss
Is this option same with your paper experiment setting?
Then use only L1 loss is sufficient for denoising task?

Thank you!

**Comment by mayorx** [comment]
Hi, hwayoon2, 
Thanks for your attention to HINet.
Due to the limitations of resources, we did not try PSNR loss in the denoising task, and the L1 loss is sufficient.
According to the deblurring task, PSNR loss brought ~0.01 dB PSNR boost.

Thanks!

**Comment by hwayoon2** [comment]
I got it, thanks for your reply
Have a good day!
