### ISSUE TITLE
About the real rain dataset

### ISSUE THREAD

**Issue by hellogry** [megvii-model/HINet#6]
I would like to compare the performance of these two real rain images, can you send me the result image?
![image](https://user-images.githubusercontent.com/12219867/119629272-6f55a400-be40-11eb-9d4b-694359743a93.png)

**Comment by mayorx** [comment]
Hi, hellogry,

We have noticed the demand for single image inference, ie. https://github.com/megvii-model/HINet/issues/4
I think it will be available soon : )

**Comment by mayorx** [comment]
Hi, hellogry, 
We have provided [single image inference](https://github.com/megvii-model/HINet#quick-start-single-image-inference) demo (GoPro in default).
