### ISSUE TITLE
What is the lincense of the Denoise project？

### ISSUE THREAD

**Issue by ai-Ilike** [megvii-model/HINet#7]

**Comment by mayorx** [comment]
Hi, ai-like,

This project is under the MIT license, and it is based on [BasicSR](https://github.com/xinntao/BasicSR) which is under the Apache 2.0 license.

Thanks for your issue and we will update the license information soon.

**Comment by mayorx** [comment]
Hi, ai-Ilike,
We have updated the license information, as you can see in [here](https://github.com/megvii-model/HINet/blob/main/LICENSE) : )

**Comment by ai-Ilike** [comment]
Thank you for your reply!
What about its model lincense?

**Comment by mayorx** [comment]
> Thank you for your reply!
> What about its model lincense?

Hi ai-Ilike,  it's under the MIT license too, feel free to use it : )
