### ISSUE TITLE
Request for denoising demo

### ISSUE THREAD

**Issue by ansariyusuf** [megvii-model/HINet#9]
Hi,

I really appreciate placing a demo for deblurring on GoPro images. Can you also provide a demo for denoising with SIDD models? It will be really helpful if you can provide some description of how the .yml parameters impact the inference on images with different pre-trained models.

Thank you very much!

Yusuf

**Comment by mayorx** [comment]
Hi, Yusuf, 
Please refer to this issue https://github.com/megvii-model/HINet/issues/8 .
